#!/bin/bash

set -e


CONFFILE_NAME="peekaygee.json"
SELF="$(basename "$0")"


function echo_push_usage() {
    echo
    echo "SYNOPSIS"
    echo "      $SELF [remote]"
    echo
    echo "DESCRIPTION"
    echo "      Push one or more packages (found using global and repo-specific config files)"
    echo "      to the given remote archive."
    echo
    echo "OPTIONS"
    echo "      -h|--help"
    echo "          Show this help text."
    echo
    echo
}


# Loop to gather options
VERBOSITY=0
while [ "$#" -gt 0 ]; do
    case "$1" in
        -h|--help)
            echo_push_usage
            exit
        ;;

        -q) VERBOSITY=-1; shift ;;
        -v) !((VERBOSITY++)); shift ;;
        -vv) VERBOSITY=2; shift ;;
        -vvv) VERBOSITY=3; shift ;;

        --version)
            echo
            echo "$SELF version $PKG_VERSION"
            echo
            echo "See readme and license information, file bug reports, and view source code at"
            echo "https://github.com/kael-shipman/peekaygee"
            echo
            exit
        ;;

        *)
            if [ -z "$REMOTE" ]; then
                REMOTE="$1"
                shift
            else
                >&2 echo_push_usage
                >&2 echo
                >&2 echo "E: You've passed an invalid command or option: $1"
                >&2 echo
                exit 6
            fi
        ;;
    esac
done


# Validate empties
if [ -z ${REMOTE+x} ]; then
    >&2 echo_push_usage
    >&2 echo
    >&2 echo "E: You haven't passed a remote!"
    >&2 echo
    exit 7
fi


# Load libraries

# Load libpeekaygee
if [ -z "$D" ]; then
    D="$(dirname "$(readlink -f "$0")")"
    for libdir in "$D" "$PEEKAYGEE_LIBDIR" /usr/lib/peekaygee; do
        if [ -e "$libdir/libpeekaygee.sh" ]; then
            . "$libdir/libpeekaygee.sh"
            lib_loaded=true
            break
        fi
    done
fi
if [ "$lib_loaded" != "true" ]; then
    >&2 echo
    >&2 echo "E: Couldn't find peekaygee libraries! Are you sure you've installed"
    >&2 echo "   peekaygee correctly?"
    >&2 echo
    exit 5
fi

# Load librexec
if [ "$lib_rexec_loaded" != "true" ]; then
    say 1 "Loading librexec"
    if [ -z "$LIBREXEC_DIR" ]; then 
        say 1 "LIBREXEC_DIR not set. Setting..."
        LIBREXEC_DIR="$(readlink -f "$(dirname "$(readlink -f "$0")")/../../librexec/src")" \
        || \
        LIBREXEC_DIR=
        say 2 "LIBREXEC_DIR set to '$LIBREXEC_DIR'"
    fi
    for libdir in "$LIBREXEC_DIR" "$REXEC_LIBDIR" /usr/lib/librexec; do
        say 3 "Checking for librexec at '$libdir/librexec.sh'"
        if [ -e "$libdir/librexec.sh" ]; then
            say 3 "Found. Loading librexec"
            . "$libdir/librexec.sh"
            lib_rexec_loaded="true"
            break
        else
            say 3 "Not found."
        fi
    done

    if [ "$lib_rexec_loaded" != "true" ]; then
        >&2 echo
        >&2 echo "E: Couldn't find librexec! Make sure you install librexec before proceeding. (Note: you"
        >&2 echo "   can set the directory to search for librexec using the \`LIBREXEC_DIR\` environment"
        >&2 echo "   variable.)"
        >&2 echo
        exit 10
    else
        say 1 "librexec loaded"
    fi
else
    say 1 "librexec already loaded"
fi


say 0 "Attempting to push packages to '$REMOTE'"
say 0


# Validate config
if ! config_jq '.' >/dev/null; then
    exit "${PIPESTATUS[0]}"
else
    say 1 "Config loaded"
fi


# Check config to make sure remote exists
if ! config_jq -e '.remotes."'$REMOTE'"' >/dev/null; then
    >&2 echo_push_usage
    >&2 echo
    >&2 echo "E: '$REMOTE' does not appear to be a configured remote. (Checked in config"
    >&2 echo "   files $(find_config_files))"
    >&2 echo
    exit 8
else
    say 1 "Remote '$REMOTE' exists in config"
fi
REMOTE_PATH="$(config_jq -r '.remotes."'$REMOTE'".url')"
say 2 "Remote path: '$REMOTE_PATH'"

# Make sure peekaygee-archive is installed
if ! rexec "$REMOTE_PATH" "command -v peekaygee-archive &>/dev/null"; then
    >&2 echo
    >&2 echo "E: It doesn't look like the remote '$REMOTE' has peekaygee-archive installed. Please"
    >&2 echo "   install peekaygee-archive on the remote before continuing."
    >&2 echo
    exit 11
else
    say 1 "peekaygee-archive is installed on remote '$REMOTE'"
fi

# Make sure archive is initialized
say 2 "Initializing archive on remote '$REMOTE'"
if ! rexec "$REMOTE_PATH" 'peekaygee-archive init "::path::"'; then
    >&2 echo
    >&2 echo "E: Couldn't initialize '$REMOTE_PATH'. Can't continue."
    >&2 echo
    exit 12
else
    say 2 "Remote initialized"
fi


# All good now. Find packages, verify acceptability, and push to remote.

SEARCH_DIRS="$(config_jq -r '."build-dirs" | join("'$'\30''")')"
if [ -z "$SEARCH_DIRS" ]; then
    >&2 echo
    >&2 echo "E: You must specify a 'build-dirs' key in your config that contains an array of build directories"
    >&2 echo "   to search for packages."
    >&2 echo
    exit 9
else
    say 3 "Search dirs: '$(echo "$SEARCH_DIRS" | tr $'\30' ' ')'"
fi

PRESERVE_PUSHED="$(config_jq -r '."preserve-pushed"')"
if [ "$PRESERVE_PUSHED" != "true" ]; then
    say 3 "Preserve pushed (raw value): $PRESERVE_PUSHED"
    PRESERVE_PUSHED="false"
fi
say 2 "Preserve pushed packages: $PRESERVE_PUSHED"

IFS=$'\30'
PKGCNT=0
ERRORS=0
for prf in $(config_jq -r '.packages | keys | join("'$'\30''")'); do
    say 1 "Processing package profile '$prf'"
    prfconf="$(config_jq ".packages.\"$prf\"")"

    # Accepting null allows us to unset previously set package profiles
    if [ "$prfconf" == "null" ]; then
        say 2 "Profile '$prf' has been overridden with 'null'. Skipping."
        continue
    fi

    say 2 "Profile '$prf': $prfconf"

    # Set other variables
    TYPE="$(echo $prfconf | jq -r '.type')"
    MATCH="$(echo $prfconf | jq -r '.match')"
    VISIBILITY="$(echo $prfconf | jq -r '.visibility')"
    OPTIONS="$(echo $prfconf | jq '.options')"

    # Default to "public" visibility, but verify value
    if [ "$VISIBILITY" == "null" ]; then
        say 3 "Visibility null; defaulting to 'public'"
        VISIBILITY=public
    elif [ "$VISIBILITY" != "public" ] && [ "$VISIBILITY" != "private" ]; then
        >&2 echo
        >&2 echo "E: Unrecognized visibility: '$VISIBILITY'. Should be 'public' or 'private'. Skipping"
        >&2 echo "   $prf files."
        >&2 echo
        !((ERRORS++))
        continue
    fi

    # Search build dirs for matching packages
    PKGS=
    say 2 "Searching for packages...." 
    for d in "$SEARCH_DIRS"; do
        if [ ! -d "$d" ]; then
            >&2 echo "W: Search directory '$d' is not a directory. Skipping...."
            continue
        fi
        while read pkg; do
            say 3 "Adding package '$pkg' to list"
            if [ -n "$PKGS" ]; then
                PKGS="$PKGS"$'\30'
            fi
            PKGS="${PKGS}$pkg"
        done < <(find "$d" -type f | egrep "$MATCH")
    done

    say 2
    say 2 "Ready to push packages"
    say 2
    say 2 "Type: $TYPE"
    say 2 "Match: $MATCH"
    say 2 "Visibility: $VISIBILITY"
    say 2 "Options: $OPTIONS"
    say 2 "Packages: $(echo "$PKGS" | tr $'\30' ' ')"
    say 2

    # Make sure there are packages to push
    if [ -z "$PKGS" ]; then
        >&2 echo
        >&2 echo "W: No packages found for type '$TYPE'"
        >&2 echo
        continue
    fi

    # Make sure the remote supports this type of package
    say 3 "Checking remote for support or '$TYPE' packages"
    if ! rexec "$REMOTE_PATH" "peekaygee-archive supports '$TYPE'" >/dev/null; then
        >&2 echo
        >&2 echo "E: Remote '$REMOTE' doesn't support archive type '$TYPE'. Skipping the following packages:"
        >&2 echo
        >&2 echo "   $(echo "$PKGS" | sed 's/'$'\30''/\n   /g')"
        >&2 echo
        !((ERRORS++))
        continue
    else
        say 2 "Remote supports package type '$TYPE'"
    fi

    # Push each package up, creating an options file for it also, if applicable
    for pkg in $PKGS; do
        success="true"
        say 0 "   - pushing '$pkg' to $VISIBILITY archive..."
        if ! rsync -u "$pkg" "$REMOTE_PATH/incoming/$VISIBILITY/"; then
            success="false"
            >&2 echo
            >&2 echo "     E: Couldn't push package '$pkg' to remote '$REMOTE' at '$REMOTE_PATH'"
            >&2 echo
            !((ERRORS++))
        else
            # If push succeeded, create an options file
            if [ "$OPTIONS" != "null" ]; then
                optsfile="$(basename "$pkg").opts"
                say 1 "  - creating options file '$optsfile'"

                # If the options file creation fails, roll back
                if ! rexec "$REMOTE_PATH" "echo '$OPTIONS' > ::path::/incoming/$VISIBILITY/$optsfile"; then
                    success="false"
                    !((ERRORS++))
                    >&2 echo
                    >&2 echo "     E: Couldn't create options file for package '$pkg'. Rolling back..."
                    >&2 echo
                    rexec "$REMOTE_PATH" "rm ::path::/incoming/$VISIBILITY/$(basename "$pkg")" || true
                fi
            else
                say 2 "No options file created."
            fi

            # If we were successful, increment and optionally delete local package
            if [ "$success" == "true" ]; then
                !((PKGCNT++))
                if [ "$PRESERVE_PUSHED" != "true" ]; then
                    rm "$pkg" || true
                fi
            fi
        fi
    done
done
unset IFS


# Done pushing, now update the remote and report
say 0
if [ "$PKGCNT" -gt 0 ]; then
    err=
    if [ "$ERRORS" -gt 0 ]; then
        err=" (with $ERRORS errors)"
    fi
    say 0 "Pushed $PKGCNT packages; now calling update on remote...."

    # Now that all packages have been uploaded, update the archive
    if ! rexec "$REMOTE_PATH" 'peekaygee-archive update "::path::"'; then
        >&2 echo
        >&2 echo "E: Remote update failed. Packages may not be published."
        >&2 echo
        exit 30
    else
        say 0 "Update successful. Packages pushed."
    fi
else
    if [ "$ERRORS" -gt 0 ]; then
        say 0 "Nothing pushed, although there were $ERRORS errors."
    else
        say 0 "Nothing pushed; all done."
    fi
fi

